### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#210]
Volto-Light-Theme should have a mobile menu that goes three levels deep like on www.dlr.de.

# ToDo

* [x] create a design in Figma
* [x] agree on a best practice implementation
* [x] implement the mobile menu by transferring best practices from other projects
