### ISSUE TITLE
Example Content

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#8]
# ToDo

## Content Types

* [x] Page /de/beispiele/page
* [x] News Item /de/beispiele/news-item
* [x] Event /de/beispiele/event
* [x] Link /de/beispiele/link
* [x] File /de/beispiele/file
* [x] Image /de/beispiele/image

## Blocks

* [x] Grid-Block /de/beispiele/block/grid
* [x] Teaser-Block /de/beispiele/block/teaser
* [x] Slider-Block
* [x] Button-Block
* [x] Separator-Block
* [ ] Introduction-Block
* [ ] Icons-Block (name tbd)

## Other Pages

* [x] Typography -> Page
* [x] Front-Page /de

# Implementation Options

* Pass a folder with content creator JSON to the docker container and just make it appear
* add it to XXX-intranet project (for now)
